version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - ATLAS_URI=mongodb+srv://faisal123:faisal123@cluster0.aw3ns.mongodb.net/hospitally-app?retryWrites=true&w=majority&appName=Cluster0
      - PORT=5000
    restart: unless-stopped