name: Deploy Backend to Azure VM

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'  # Only trigger when backend files change

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      working-directory: ./backend  # Important: work in backend directory
      run: docker build . --file Dockerfile --tag mern-backend
    
    - name: Save Docker image
      run: docker save mern-backend -o mern-backend.tar
    
    - name: Copy files to Azure VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        password: ${{ secrets.AZURE_VM_PASSWORD }}
        port: 22
        source: "mern-backend.tar,backend/docker-compose.yml"  # Note path to compose file
        target: "/home/azureuser/"
    
    - name: SSH and deploy on Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        password: ${{ secrets.AZURE_VM_PASSWORD }}
        port: 22
        script: |
          docker load -i /home/azureuser/mern-backend.tar
          docker-compose -f /home/azureuser/docker-compose.yml down
          docker-compose -f /home/azureuser/docker-compose.yml up -d