name: Auto Deploy Backend

on:
  push:
    branches: [main]
    paths: 
      - 'backend/**'  # Only deploy if backend files change

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build & Push Docker Image
        run: |
          cd backend
          docker build -t mern-backend .
          docker save mern-backend > mern-backend.tar
          scp -o StrictHostKeyChecking=no mern-backend.tar docker-compose.yml ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/mern-backend/Hospitally-App/backend/

      - name: Run on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<EOF
            cd ~/mern-backend/Hospitally-App/backend
            docker load -i mern-backend.tar
            docker compose down
            docker compose up -d
          EOF