name: Deploy Vite React App to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Vite React App
        run: |
          cd frontend
          npm run build

      - name: Prepare Deployment Artifacts
        run: |
          mkdir deploy
          cp -r frontend/build/* deploy/
          cp server.js deploy/
          cp package.json deploy/  # If your server has its own dependencies
          cp -r node_modules deploy/ || echo "No node_modules to copy"

      - name: Zip for Azure
        run: |
          cd deploy
          zip -r ../app.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <YOUR_AZURE_APP_NAME>
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: app.zip
